import {
  REACT_APP_NATIVE_SUPABASE_URL,
  REACT_APP_NATIVE_SUPABASE_ANON_KEY,
} from "@env";

export const supabaseUrl = REACT_APP_NATIVE_SUPABASE_URL;
export const supabaseAnonKey = REACT_APP_NATIVE_SUPABASE_ANON_KEY;
